---
title: "19F in Germany"
author: "Paloma Cárcamo"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
if (!require("pacman")) install.packages("pacman")
pacman::p_load(tidyverse, sf, spdep, INLA, cowplot)
```

### 3-digit zipcode

Missing zipcode: 5685/39315

Shapefiles from GADM https://gadm.org/download_country.html

Vaccination coverage estimates from Robert Kock Institut https://robert-koch-institut.github.io/Inanspruchnahme_von_Routineimpfungen_in_Deutschland-Ergebnisse_aus_der_KV-Impfsurveillance/

```{r}
ger_ipd_raw <- read_csv("data/DE_IPD_deidentified.csv")

ger_ipd <- ger_ipd_raw |> 
  mutate(date = as.Date(DateOfIsolation, format = "%d/%m/%Y")) |> 
  filter(!is.na(PLZpatient) & date > as.Date("2009-01-01")) |> 
  mutate(plz = str_pad(PLZpatient, side = "left", pad = "0", width = 3)) |> 
  group_by(plz, Serotype) |> 
  summarise(ipd_st = n()) |> 
  group_by(plz) |> 
  mutate(ipd = sum(ipd_st)) |> 
  ungroup() |> 
  filter(Serotype == "19F") |> 
  mutate(ratio_19F = ipd_st/ipd)

ger_shp <- read_sf("data/gadm41_DEU_2.shp")

ger_shp_plz <- read_sf("data/plz-2stellig.shp") |> 
  st_transform(st_crs(ger_shp))

ger_cov <- readxl::read_xlsx("data/kvis_vax.xlsx")

ger_key_raw <- read_csv("data/zuordnung_plz_ort.csv")

ger_key <- ger_key_raw |> 
  mutate(ags2 = substr(ags, 1, 5),
         plz2 = substr(plz, 1, 2)) |> 
  distinct(ags2, plz2)
```

```{r}
ger_covsf <- ger_shp |> 
  right_join(ger_cov, by = c("CC_2" = "county_ags")) |> 
  filter(vaccine == "Pneumokokken")
```

```{r, fig.width = 14, fig.height = 10}
ger_covsf |> 
  ggplot() +
  geom_sf(aes(fill = vacc_rate), color = NA) +
  scale_fill_viridis_c() +
  facet_wrap(~year_birth) +
  theme_void() +
  labs(fill = "Vaccine coverage", title = "Pneumococcal vaccine coverage by AGS and year of birth")
```

```{r, fig.height = 10}
ger_shp |> 
  ggplot() +
  geom_sf(data = ger_shp_plz, aes(fill = plz), color = NA, show.legend = FALSE) +
  geom_sf(color = "black", fill = NA) +
  theme_void()
```


### Aggregate vax rates to first two digits of plz

(toma infinito tiempo en correr)

```{r}
# ger_shp_j <- ger_shp |> 
#   mutate(ags_area = st_area(geometry))
# 
# st_intersection_faster <- function(x, y) {
#   y_indices <- st_intersects(x, y) |> 
#     unlist() |> 
#     unique() |> 
#     sort()
#   
#   y_subset <- y[y_indices, ]
#   st_intersection(x, y_subset)
# }
# 
# intersection_pre <- st_intersection_faster(ger_shp, ger_shp_plz)
# 
# intersection <- intersection_pre |> 
#   mutate(intersection_area = st_area(geometry),
#          district_area = ger_shp_j$ags_area[match(intersection_pre$CC_2, ger_shp$CC_2)], 
#          overlap_percentage = (intersection_area / district_area) * 100)
# 
# plz_ags_key <- intersection |> 
#   st_drop_geometry() |> 
#   dplyr::select(CC_2, plz, overlap_percentage) |> 
#   arrange(CC_2, plz)
# 
# # write_rds(intersection_pre, "data/interim/intersection_pre.rds")
# # write_rds(intersection, "data/interim/intersection.rds")
# # write_rds(plz_ags_key, "data/interim/plz_ags_key.rds")

plz_ags_key <- read_rds("data/interim/plz_ags_key.rds")
```

```{r}
ger_cov_agg <- ger_cov |> 
  filter(vaccine == "Pneumokokken") |> 
  left_join(plz_ags_key, by = c("county_ags" = "CC_2")) |> 
  mutate(new_pop = pop_weight*overlap_percentage,
         vaxed = new_pop*(vacc_rate/100)) |> 
  group_by(plz, year_birth) |> 
  summarise(vax_pop = sum(vaxed, na.rm = TRUE),
            all_pop = sum(new_pop, na.rm = TRUE)) |> 
  mutate(vacc_rate = as.numeric(vax_pop/all_pop))

ger_cov_sum <- ger_cov_agg |> 
  group_by(plz) |> 
  summarise(vacc_rate = mean(vacc_rate, na.rm = TRUE))
```

### First two digits of plz

```{r}
ger_ipd_plz2 <- ger_ipd_raw |> 
  mutate(date = as.Date(DateOfIsolation, format = "%d/%m/%Y")) |> 
  filter(!is.na(PLZpatient) & date > as.Date("2009-01-01")) |> 
  mutate(plz = str_pad(PLZpatient, side = "left", pad = "0", width = 3),
         plz_2 = substr(plz, 1, 2)) |> 
  group_by(plz_2, Serotype) |> 
  summarise(ipd_st = n()) |> 
  group_by(plz_2) |> 
  mutate(ipd = sum(ipd_st)) |> 
  ungroup() |> 
  filter(Serotype == "19F") |> 
  mutate(ratio_19F = ipd_st/ipd)

ger_ipd_plz2_sf <- ger_shp_plz |> 
  left_join(ger_ipd_plz2, by = c("plz" = "plz_2")) |> 
  mutate(plz = factor(plz)) |> 
  ungroup()
```

```{r}
ger_ipd_plz2_sf |> 
  ggplot() +
  geom_sf(aes(fill = ratio_19F), color = NA) +
  scale_fill_viridis_c() +
  theme_void()
   
ger_shp_plz |> 
  right_join(ger_cov_sum, by = "plz") |> 
  ggplot() +
  geom_sf(aes(fill = vacc_rate), color = NA) +
  scale_fill_viridis_c() +
  theme_void()
```

```{r}
ger_shp_plz |> 
  right_join(ger_cov_agg, by = "plz") |> 
  ggplot() +
  geom_sf(aes(fill = vacc_rate), color = NA) +
  scale_fill_viridis_c() +
  facet_wrap(~year_birth) +
  theme_void()
```

#### INLA - BYM

```{r}
nb3 <- poly2nb(ger_shp_plz, queen = TRUE)
nb2INLA("map_plz2.adj", nb3)
g_plz2 <- inla.read.graph(filename = "map_plz2.adj")

plz2_db <- ger_shp_plz |> 
  st_drop_geometry() |> 
  ungroup() |> 
  mutate(idarea = row_number())

data_inla_plz2 <- list(
  cases_19F = plz2_db$ipd_st,
  total_cases = plz2_db$ipd,
  N = plz2_db$ipd,
  idarea = plz2_db$idarea
)

f4 <- cases_19F ~ 1 + f(idarea, model = "bym2", graph = g_plz2)

result_bym_plz2 <- inla(
  f4, 
  family = "binomial",
  data = data_inla_plz2, 
  Ntrials = data_inla_plz2$N, 
  control.predictor = list(compute = TRUE), 
  control.compute = list(dic = TRUE, waic = TRUE),
  verbose = TRUE
)

summary(result_bym_plz2)

bym_st_plz2 <- ger_ipd_plz2_sf |> 
  cbind(result_bym_plz2$summary.random$idarea[1:95, ]) |> 
  mutate(sig = case_when(X0.025quant > 0 & X0.975quant > 0 ~ 1,
                         X0.025quant > 0 & X0.975quant < 0 ~ 1,
                         .default = 0))

bym_unst_plz2 <- ger_ipd_plz2_sf |> 
  cbind(result_bym_plz2$summary.random$idarea[96:190, ]) |> 
  mutate(sig = case_when(X0.025quant > 0 & X0.975quant > 0 ~ 1,
                         X0.025quant > 0 & X0.975quant < 0 ~ 1,
                         .default = 0))

plz2_structured <- bym_st_plz2 |> 
  ggplot() +
  geom_sf(aes(fill = mean), color = NA) +
  scale_fill_viridis_c() +
  labs(title = "Structured effects") +
  theme_void()

plz2_unstructured <- bym_unst_plz2 |> 
  ggplot() +
  geom_sf(aes(fill = mean), color = NA) +
  scale_fill_viridis_c() +
  labs(title = "Unstructured effects") +
  theme_void()

plot_grid(plz2_structured, plz2_unstructured, ncol = 2)
```
